version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  books-service:
    image: books-service
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore.settings
      - DATABASE_HOST=db
    depends_on:
      - db
    ports:
      - "8001:8000"  # Maps container port 8000 to host port 8001
volumes:
  postgres_data: