apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: bookstore-app
spec:
  type: LoadBalancer
  ports: 
  - name: http
    port: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: bookstore-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service # bookstore-deploy
  labels:
    app: bookstore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
      - name: bookstore-service
        image: sgs1/books-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: BOOKDB_IP
          valueFrom:
            configMapKeyRef:
              name: book-service-config
              key: bookdb_ip
