apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

# apiVersion: v1
# kind: Service
# metadata:
#   name: db-service
#   labels:
#     app: bookstore
# spec:
#   ports:
#   - port: 27017
#     targetPort: postgres-port
#   selector:
#     app: bookstore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore
  labels:
    app: bookstore
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: postgres
        ports:
        - containerPort: 27017
          name: postgres-port
        volumeMounts:
        - name: db-data
          mountPath: /data/db
        - name: postgres-config
          mountPath: /data/configdb
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: postgres-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Mi